# Generated by Django 4.2.7 on 2025-04-20 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("historical", "Historical"),
                            ("natural", "Natural"),
                            ("cultural", "Cultural"),
                            ("religious", "Religious"),
                            ("adventure", "Adventure"),
                            ("beach", "Beach"),
                            ("mountain", "Mountain"),
                            ("city", "City"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("addis_ababa", "Addis Ababa"),
                            ("afar", "Afar"),
                            ("amhara", "Amhara"),
                            ("benishangul_gumuz", "Benishangul-Gumuz"),
                            ("diredawa", "Dire Dawa"),
                            ("gambela", "Gambela"),
                            ("harari", "Harari"),
                            ("oromia", "Oromia"),
                            ("sidama", "Sidama"),
                            ("somali", "Somali"),
                            ("south_west", "South West"),
                            ("southern", "Southern"),
                            ("tigray", "Tigray"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("images", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DestinationReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("helpful", models.IntegerField(default=0)),
                ("reported", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedDestination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destinations.destination",
                    ),
                ),
            ],
        ),
    ]
